version: '2'

services:
    db:
        image: mysql:5.7.21
        hostname: dbserver
        ports:
        - "3306:3306"
        volumes:
        - ./db_data:/var/lib/mysql
        environment:
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=boot_db

    app:
        image: openjdk:8-jdk-alpine
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        working_dir: /app
        command: ./mvnw spring-boot:run